language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "nightly"
  - "pypy"

install:
  - travis_retry pip install pylint
  - travis_retry pip install -r requirements.txt
  - travis_retry pip install -r tests/requirements.txt
  - travis_retry pip install pytest-cov coverage coveralls

caches:
  directories:
    - $HOME/.cache/pip

script:
  py.test --cov=all

after_success:
  coveralls
